import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import frequencyReport from "../../data/frequency-report.json";
import { PageHeader, PageBody } from "../../components/shell/AppShell";
import { RequireAuth } from "../../components/shell/RequireAuth";
import { Panel, PanelHeader, Tag, Skeleton } from "../../components/ui/Primitives";
import { CountUp } from "../../components/ui/CountUp";
import { RiskMix, PremiumBands, ClaimsTrend, RiskPremiumScatter, RankedBars } from "../../components/insurer/Charts";
import { useT } from "../../context/I18nContext";
import { api, type DashboardData } from "../../lib/api";
import { gsap, useGSAP, reducedMotion } from "../../lib/motion";
import { inr, inrCompact, num } from "../../lib/utils";

const FREQ_MODELS = (frequencyReport.models as { id: string; test: { gini: number; devianceExplained: number } }[]).filter((m) => m.id !== "null");

const SEGMENT_LABEL: Record<string, string> = {
  "Low Risk / High Value": "Low risk, high value",
  "Low Risk / Low Value": "Low risk, low value",
  "Moderate Risk": "Moderate risk",
  "High Risk": "High risk",
  "High Value / High Risk": "High risk, high value",
  "Potential Fraud/Anomaly": "Flagged for review",
};

function Kpi({ label, value, format, hint }: { label: string; value: number; format: (n: number) => string; hint?: string }) {
  return (
    <div className="px-4 py-3.5">
      <p className="text-2xs text-fg-subtle">{label}</p>
      <CountUp value={value} format={format} className="num mt-1 block text-xl font-semibold tracking-[-0.02em] text-fg" />
      {hint && <p className="mt-0.5 text-2xs text-fg-subtle">{hint}</p>}
    </div>
  );
}

function OverviewInner() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const root = useRef<HTMLDivElement>(null);
  const t = useT();

  useEffect(() => {
    api.dashboard().then(setData).catch((e) => setError(e.message));
  }, []);

  useGSAP(
    () => {
      if (!data || reducedMotion()) return;
      gsap.from("[data-reveal]", { opacity: 0, y: 10, duration: 0.5, stagger: 0.05, ease: "power2.out" });
    },
    { scope: root, dependencies: [!!data] },
  );

  const k = data?.kpis;
  return (
    <div ref={root}>
      <PageHeader
        meta={<Tag tone="warning" dot>{t("Synthetic sample data")}</Tag>}
        title={t("Portfolio overview")}
        description={t("500 made-up policyholders generated by the seed script and priced with the same engine visitors use. It shows what an underwriting team would see across a book. None of it is real customer data.")}
        actions={<Link to="/insurers/policies" className="inline-flex items-center gap-1 text-sm text-fg-muted hover:text-fg">{t("All policies")} <ArrowRight className="size-3.5" /></Link>}
      />
      <PageBody className="space-y-4">
        {error && <p className="text-sm text-danger">{error}</p>}

        <div data-reveal className="grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-5 [&>*]:bg-surface">
          {!k
            ? Array.from({ length: 10 }).map((_, i) => <div key={i} className="px-4 py-3.5"><Skeleton className="h-3 w-16" /><Skeleton className="mt-2 h-6 w-20" /></div>)
            : (
              <>
                <Kpi label={t("Policies")} value={k.totalPolicies} format={(n) => num(Math.round(n))} />
                <Kpi label={t("Annual premium income")} value={k.premiumRevenue} format={inrCompact} />
                <Kpi label={t("Average premium")} value={k.averagePremium} format={inr} />
                <Kpi label={t("Average risk score")} value={k.averageRiskScore} format={(n) => n.toFixed(1)} />
                <Kpi label={t("Loss ratio")} value={k.lossRatio} format={(n) => `${n.toFixed(1)}%`} hint={t("Claims paid ÷ premium, 12 months")} />
                <Kpi label={t("Sum insured")} value={k.totalInsuredValue} format={inrCompact} />
                <Kpi label={t("High-risk policyholders")} value={k.highRiskCustomers} format={(n) => num(Math.round(n))} hint={t("Risk score above 60")} />
                <Kpi label={t("Consistency flags")} value={k.potentialAnomalies} format={(n) => num(Math.round(n))} hint={t("For manual review")} />
                <Kpi label={t("Claims per policy")} value={k.claimsFrequency} format={(n) => n.toFixed(2)} hint={t("Per year")} />
                <Kpi label={t("Open claims exposure")} value={k.estimatedClaimsExposure} format={inrCompact} />
              </>
            )}
        </div>

        <div className="grid gap-4 lg:grid-cols-2">
          <Panel data-reveal>
            <PanelHeader title={t("Risk mix")} description={t("Policies by risk band")} />
            <div className="p-4">{data ? <RiskMix data={data.riskDistribution} /> : <Skeleton className="h-20" />}</div>
          </Panel>
          <Panel data-reveal>
            <PanelHeader title={t("Premium bands")} description={t("Policies by annual premium")} />
            <div className="p-4 pt-3">{data ? <PremiumBands data={data.premiumDistribution} /> : <Skeleton className="h-48" />}</div>
          </Panel>
        </div>

        <Panel data-reveal>
          <PanelHeader title={t("Risk against premium")} description={t("Each dot is a policy. Premium on a log scale, since motor, home, health and term life sit in very different price ranges.")} />
          <div className="p-4 pt-3">{data ? <RiskPremiumScatter data={data.riskVsPremium} /> : <Skeleton className="h-60" />}</div>
        </Panel>

        <div className="grid gap-4 lg:grid-cols-2">
          <Panel data-reveal>
            <PanelHeader title={t("Claims filed")} description={t("By month")} />
            <div className="p-4 pt-3">{data ? <ClaimsTrend data={data.claimsByMonth} /> : <Skeleton className="h-48" />}</div>
          </Panel>
          <Panel data-reveal>
            <PanelHeader title={t("Highest-risk cities")} description={t("Average risk score")} />
            <div className="p-4">
              {data ? (
                <RankedBars
                  tone="risk"
                  format={(n) => n.toFixed(1)}
                  rows={[...data.geographicRisk].sort((a, b) => b.averageRiskScore - a.averageRiskScore).slice(0, 8).map((g) => ({ label: g.location, value: g.averageRiskScore }))}
                />
              ) : <Skeleton className="h-48" />}
            </div>
          </Panel>
        </div>

        <div className="grid gap-4 lg:grid-cols-2">
          <Panel data-reveal>
            <PanelHeader title={t("Segments")} description={t("By risk and sum insured")} />
            <div className="p-4">{data ? <RankedBars rows={[...data.customerSegments].sort((a, b) => b.count - a.count).map((s) => ({ label: SEGMENT_LABEL[s.segment] ? t(SEGMENT_LABEL[s.segment]) : s.segment, value: s.count }))} /> : <Skeleton className="h-40" />}</div>
          </Panel>
          <Panel data-reveal>
            <PanelHeader
              title={t("Claim frequency model")}
              description={t("Poisson GLM against gradient boosting on 677,991 real motor policies")}
              actions={<Link to="/insurers/model" className="inline-flex items-center gap-1 text-xs text-accent-text hover:underline">{t("Open")} <ArrowRight className="size-3.5" /></Link>}
            />
            <dl className="grid grid-cols-2 divide-x divide-border">
              {FREQ_MODELS.map((m) => (
                <div key={m.id} className="p-4">
                  <dt className="text-2xs text-fg-subtle">{m.id === "glm" ? "Poisson GLM" : "Poisson GBM"}</dt>
                  <dd className="num mt-1 text-xl font-semibold text-fg">{m.test.gini.toFixed(3)}</dd>
                  <dd className="text-2xs text-fg-subtle">{t("Gini, test set · {pct} of deviance explained", { pct: `${(m.test.devianceExplained * 100).toFixed(1)}%` })}</dd>
                </div>
              ))}
            </dl>
          </Panel>
        </div>
      </PageBody>
    </div>
  );
}

export function InsurerOverview() {
  const t = useT();
  return (
    <RequireAuth title={t("Insurer workspace")} reason={t("The workspace shows portfolio analytics on a synthetic sample book. Sign in to open it.")}>
      <OverviewInner />
    </RequireAuth>
  );
}
