// Generated by scripts/gen-landing-sample.ts from the real engine, one entry per
// language. Don't edit by hand: the landing page must never show invented numbers.
import type { ApplicantProfile, PremiumBreakdown, RiskFactorContribution, MarketBenchmark, Recommendation, RiskCategory, Lang } from "@insurtechai/shared";

export interface LandingSample {
  applicant: ApplicantProfile;
  premium: PremiumBreakdown;
  risk: { riskScore: number; riskCategory: RiskCategory; factors: RiskFactorContribution[] };
  benchmark: MarketBenchmark;
  verdict: string;
  recommendations: Recommendation[];
  scenario: { premium: number; riskScore: number; steps: number[] };
  answer: string;
}

export const SAMPLES = {
 "en": {
  "applicant": {
   "personal": {
    "age": 29,
    "gender": "FEMALE",
    "occupation": "Product designer",
    "location": "Bengaluru",
    "annualIncome": 1800000,
    "maritalStatus": "SINGLE",
    "dependents": 0
   },
   "policy": {
    "insuranceType": "MOTOR",
    "coverageLevel": "STANDARD",
    "deductible": 0
   },
   "claimsLast12Months": 0,
   "recentClaimDatesIso": [],
   "motor": {
    "vehicleAgeYears": 3,
    "exShowroomPrice": 1400000,
    "vehicleValue": 840000,
    "claimFreeYears": 2,
    "vehicleType": "SUV",
    "engineCapacityCC": 1497,
    "annualMileageKm": 18000,
    "previousAccidents": 1,
    "previousClaims": 1,
    "drivingExperienceYears": 6,
    "trafficViolations": 1,
    "hasTrackingDevice": false
   }
  },
  "premium": {
   "basePremium": 18480,
   "riskMultiplier": 1.2,
   "coverageMultiplier": 1,
   "locationFactor": 1.11,
   "claimHistoryFactor": 1.11,
   "fraudAdjustment": 1,
   "deductibleFactor": 1,
   "ncbPercent": 25,
   "fixedPremium": 3416,
   "fixedPremiumLabel": "Third-party cover (fixed by IRDAI)",
   "finalPremium": 23910,
   "currency": "INR"
  },
  "risk": {
   "riskScore": 33,
   "riskCategory": "Low",
   "factors": [
    {
     "name": "City traffic and theft rates",
     "category": "Geographic",
     "impact": 12.5,
     "direction": "negative",
     "description": "Bengaluru rates high for traffic density and vehicle theft among the 20 cities this model covers."
    },
    {
     "name": "Previous accidents",
     "category": "HistoricalClaims",
     "impact": 6.6,
     "direction": "negative",
     "description": "One accident on record. Past accidents are the strongest predictor of future claims."
    },
    {
     "name": "Previous claims",
     "category": "HistoricalClaims",
     "impact": 4.8,
     "direction": "negative",
     "description": "One previous claim. Each claim also resets your no-claim bonus."
    },
    {
     "name": "Traffic violations",
     "category": "Behavioral",
     "impact": 3.8,
     "direction": "negative",
     "description": "One traffic violation on record."
    },
    {
     "name": "Driver age 25–29",
     "category": "Age",
     "impact": 3,
     "direction": "negative",
     "description": "Accident rates are still above average at 29, and fall through the late twenties."
    },
    {
     "name": "High annual mileage",
     "category": "Behavioral",
     "impact": 2.5,
     "direction": "negative",
     "description": "18,000 km a year means more time on the road and more exposure to accidents."
    }
   ]
  },
  "benchmark": {
   "applicable": true,
   "lowInr": 15000,
   "medianInr": 22500,
   "highInr": 30000,
   "position": "within",
   "basis": "Typical published comprehensive premium range for an SUV in India. It doesn't adjust for your vehicle's value or city.",
   "sources": [
    {
     "label": "Forbes Advisor India · Average cost of car insurance (2026)",
     "url": "https://www.forbes.com/advisor/in/car-insurance/average-cost-of-car-insurance/"
    }
   ]
  },
  "verdict": "Your risk profile is low. At ₹23,910 a year, the estimate is within the usual published range of ₹15,000–₹30,000.",
  "recommendations": [
   {
    "id": "renew-without-claim",
    "title": "Renew without claiming",
    "description": "Your no-claim bonus on the own-damage part goes from 25% to 35% at the next renewal. Paying for a small repair yourself can be cheaper than losing it.",
    "category": "HistoricalClaims",
    "estimatedSavingAmount": 2730,
    "estimatedSavingPercent": 11.4,
    "effort": "Medium",
    "impactPerEffort": 1365
   },
   {
    "id": "install-tracking-device",
    "title": "Fit an approved anti-theft device",
    "description": "An ARAI-approved device lowers theft risk, and most insurers give a discount for it.",
    "category": "Behavioral",
    "estimatedSavingAmount": 510,
    "estimatedSavingPercent": 2.1,
    "effort": "Low",
    "impactPerEffort": 510
   },
   {
    "id": "increase-deductible",
    "title": "Choose a higher voluntary deductible",
    "description": "You pay more of each claim yourself, and the premium drops. Only worth it if you could cover that amount.",
    "category": "Behavioral",
    "estimatedSavingAmount": 410,
    "estimatedSavingPercent": 1.7,
    "effort": "Low",
    "impactPerEffort": 410
   },
   {
    "id": "reduce-mileage",
    "title": "Drive fewer kilometres",
    "description": "Less time on the road means fewer chances of an accident. Some insurers offer pay-as-you-drive plans for low mileage.",
    "category": "Behavioral",
    "estimatedSavingAmount": 340,
    "estimatedSavingPercent": 1.4,
    "effort": "Medium",
    "impactPerEffort": 170
   }
  ],
  "scenario": {
   "premium": 22660,
   "riskScore": 26,
   "steps": [
    23500,
    23000,
    22660
   ]
  },
  "answer": "Renew without claiming. That would save about ₹2,730 a year (11.4%), and it's medium effort. Your no-claim bonus on the own-damage part goes from 25% to 35% at the next renewal. Paying for a small repair yourself can be cheaper than losing it."
 },
 "hi": {
  "applicant": {
   "personal": {
    "age": 29,
    "gender": "FEMALE",
    "occupation": "Product designer",
    "location": "Bengaluru",
    "annualIncome": 1800000,
    "maritalStatus": "SINGLE",
    "dependents": 0
   },
   "policy": {
    "insuranceType": "MOTOR",
    "coverageLevel": "STANDARD",
    "deductible": 0
   },
   "claimsLast12Months": 0,
   "recentClaimDatesIso": [],
   "motor": {
    "vehicleAgeYears": 3,
    "exShowroomPrice": 1400000,
    "vehicleValue": 840000,
    "claimFreeYears": 2,
    "vehicleType": "SUV",
    "engineCapacityCC": 1497,
    "annualMileageKm": 18000,
    "previousAccidents": 1,
    "previousClaims": 1,
    "drivingExperienceYears": 6,
    "trafficViolations": 1,
    "hasTrackingDevice": false
   }
  },
  "premium": {
   "basePremium": 18480,
   "riskMultiplier": 1.2,
   "coverageMultiplier": 1,
   "locationFactor": 1.11,
   "claimHistoryFactor": 1.11,
   "fraudAdjustment": 1,
   "deductibleFactor": 1,
   "ncbPercent": 25,
   "fixedPremium": 3416,
   "fixedPremiumLabel": "थर्ड-पार्टी कवर (IRDAI द्वारा तय)",
   "finalPremium": 23910,
   "currency": "INR"
  },
  "risk": {
   "riskScore": 33,
   "riskCategory": "Low",
   "factors": [
    {
     "name": "शहर में ट्रैफ़िक और चोरी की दर",
     "category": "Geographic",
     "impact": 12.5,
     "direction": "negative",
     "description": "इस मॉडल में शामिल 20 शहरों में Bengaluru ट्रैफ़िक और वाहन चोरी के मामले में ऊँचे स्तर पर है।"
    },
    {
     "name": "पिछली दुर्घटनाएँ",
     "category": "HistoricalClaims",
     "impact": 6.6,
     "direction": "negative",
     "description": "रिकॉर्ड में एक दुर्घटना है। पिछली दुर्घटनाएँ भविष्य के क्लेम का सबसे मज़बूत संकेत होती हैं।"
    },
    {
     "name": "पिछले क्लेम",
     "category": "HistoricalClaims",
     "impact": 4.8,
     "direction": "negative",
     "description": "पहले एक क्लेम हो चुका है। हर क्लेम से आपका नो-क्लेम बोनस भी ज़ीरो हो जाता है।"
    },
    {
     "name": "ट्रैफ़िक नियमों का उल्लंघन",
     "category": "Behavioral",
     "impact": 3.8,
     "direction": "negative",
     "description": "रिकॉर्ड में ट्रैफ़िक नियम तोड़ने का एक मामला है।"
    },
    {
     "name": "ड्राइवर की उम्र 25–29",
     "category": "Age",
     "impact": 3,
     "direction": "negative",
     "description": "29 की उम्र में दुर्घटना दर अभी भी औसत से ज़्यादा है, और 20 के दशक के आख़िर तक घटती जाती है।"
    },
    {
     "name": "ज़्यादा सालाना ड्राइविंग",
     "category": "Behavioral",
     "impact": 2.5,
     "direction": "negative",
     "description": "18,000 km सालाना का मतलब है सड़क पर ज़्यादा समय और दुर्घटना का ज़्यादा जोखिम।"
    }
   ]
  },
  "benchmark": {
   "applicable": true,
   "lowInr": 15000,
   "medianInr": 22500,
   "highInr": 30000,
   "position": "within",
   "basis": "भारत में SUV के लिए आम प्रकाशित कॉम्प्रिहेंसिव प्रीमियम रेंज। यह आपके वाहन की कीमत या शहर के हिसाब से नहीं बदलती।",
   "sources": [
    {
     "label": "Forbes Advisor India · Average cost of car insurance (2026)",
     "url": "https://www.forbes.com/advisor/in/car-insurance/average-cost-of-car-insurance/"
    }
   ]
  },
  "verdict": "आपकी रिस्क प्रोफ़ाइल कम है। ₹23,910 सालाना पर, यह अनुमान ₹15,000–₹30,000 की सामान्य प्रकाशित रेंज के अंदर है।",
  "recommendations": [
   {
    "id": "renew-without-claim",
    "title": "बिना क्लेम किए रिन्यू करें",
    "description": "अगले रिन्यूअल पर ओन-डैमेज हिस्से पर आपका नो-क्लेम बोनस 25% से 35% हो जाता है। छोटी मरम्मत का ख़र्च ख़ुद उठाना इसे गँवाने से सस्ता पड़ सकता है।",
    "category": "HistoricalClaims",
    "estimatedSavingAmount": 2730,
    "estimatedSavingPercent": 11.4,
    "effort": "Medium",
    "impactPerEffort": 1365
   },
   {
    "id": "install-tracking-device",
    "title": "अप्रूव्ड एंटी-थेफ़्ट डिवाइस लगवाएँ",
    "description": "ARAI-अप्रूव्ड डिवाइस चोरी का जोखिम कम करता है, और ज़्यादातर बीमा कंपनियाँ इस पर छूट देती हैं।",
    "category": "Behavioral",
    "estimatedSavingAmount": 510,
    "estimatedSavingPercent": 2.1,
    "effort": "Low",
    "impactPerEffort": 510
   },
   {
    "id": "increase-deductible",
    "title": "ज़्यादा वॉलंटरी डिडक्टिबल चुनें",
    "description": "हर क्लेम का ज़्यादा हिस्सा आप ख़ुद चुकाते हैं, और प्रीमियम घट जाता है। यह तभी फ़ायदेमंद है जब आप वह राशि चुका सकें।",
    "category": "Behavioral",
    "estimatedSavingAmount": 410,
    "estimatedSavingPercent": 1.7,
    "effort": "Low",
    "impactPerEffort": 410
   },
   {
    "id": "reduce-mileage",
    "title": "कम किलोमीटर गाड़ी चलाएँ",
    "description": "सड़क पर कम समय का मतलब है दुर्घटना की कम संभावना। कुछ बीमा कंपनियाँ कम ड्राइविंग के लिए pay-as-you-drive प्लान देती हैं।",
    "category": "Behavioral",
    "estimatedSavingAmount": 340,
    "estimatedSavingPercent": 1.4,
    "effort": "Medium",
    "impactPerEffort": 170
   }
  ],
  "scenario": {
   "premium": 22660,
   "riskScore": 26,
   "steps": [
    23500,
    23000,
    22660
   ]
  },
  "answer": "बिना क्लेम किए रिन्यू करें। इससे सालाना लगभग ₹2,730 (11.4%) की बचत होगी, और इसमें मेहनत मध्यम है। अगले रिन्यूअल पर ओन-डैमेज हिस्से पर आपका नो-क्लेम बोनस 25% से 35% हो जाता है। छोटी मरम्मत का ख़र्च ख़ुद उठाना इसे गँवाने से सस्ता पड़ सकता है।"
 },
 "mr": {
  "applicant": {
   "personal": {
    "age": 29,
    "gender": "FEMALE",
    "occupation": "Product designer",
    "location": "Bengaluru",
    "annualIncome": 1800000,
    "maritalStatus": "SINGLE",
    "dependents": 0
   },
   "policy": {
    "insuranceType": "MOTOR",
    "coverageLevel": "STANDARD",
    "deductible": 0
   },
   "claimsLast12Months": 0,
   "recentClaimDatesIso": [],
   "motor": {
    "vehicleAgeYears": 3,
    "exShowroomPrice": 1400000,
    "vehicleValue": 840000,
    "claimFreeYears": 2,
    "vehicleType": "SUV",
    "engineCapacityCC": 1497,
    "annualMileageKm": 18000,
    "previousAccidents": 1,
    "previousClaims": 1,
    "drivingExperienceYears": 6,
    "trafficViolations": 1,
    "hasTrackingDevice": false
   }
  },
  "premium": {
   "basePremium": 18480,
   "riskMultiplier": 1.2,
   "coverageMultiplier": 1,
   "locationFactor": 1.11,
   "claimHistoryFactor": 1.11,
   "fraudAdjustment": 1,
   "deductibleFactor": 1,
   "ncbPercent": 25,
   "fixedPremium": 3416,
   "fixedPremiumLabel": "थर्ड-पार्टी कव्हर (IRDAI ने ठरवलेले)",
   "finalPremium": 23910,
   "currency": "INR"
  },
  "risk": {
   "riskScore": 33,
   "riskCategory": "Low",
   "factors": [
    {
     "name": "शहरातील वाहतूक आणि चोरीचे प्रमाण",
     "category": "Geographic",
     "impact": 12.5,
     "direction": "negative",
     "description": "हे मॉडेल ज्या 20 शहरांचा विचार करते, त्यांपैकी Bengaluru मध्ये वाहतुकीची गर्दी आणि वाहनचोरीचे प्रमाण जास्त आहे."
    },
    {
     "name": "मागील अपघात",
     "category": "HistoricalClaims",
     "impact": 6.6,
     "direction": "negative",
     "description": "नोंदीवर एक अपघात आहे. भविष्यातील क्लेमचा सर्वात मजबूत संकेत म्हणजे मागील अपघात."
    },
    {
     "name": "मागील क्लेम",
     "category": "HistoricalClaims",
     "impact": 4.8,
     "direction": "negative",
     "description": "यापूर्वी एक क्लेम. प्रत्येक क्लेममुळे तुमचा नो-क्लेम बोनसही शून्यावर येतो."
    },
    {
     "name": "वाहतूक नियमभंग",
     "category": "Behavioral",
     "impact": 3.8,
     "direction": "negative",
     "description": "नोंदीवर एक वाहतूक नियमभंग."
    },
    {
     "name": "चालकाचे वय 25–29",
     "category": "Age",
     "impact": 3,
     "direction": "negative",
     "description": "29 व्या वर्षी अपघातांचे प्रमाण अजूनही सरासरीपेक्षा जास्त असते, आणि विशीच्या उत्तरार्धात ते कमी होत जाते."
    },
    {
     "name": "जास्त वार्षिक प्रवास",
     "category": "Behavioral",
     "impact": 2.5,
     "direction": "negative",
     "description": "वर्षाला 18,000 km म्हणजे रस्त्यावर जास्त वेळ आणि अपघाताचा जास्त धोका."
    }
   ]
  },
  "benchmark": {
   "applicable": true,
   "lowInr": 15000,
   "medianInr": 22500,
   "highInr": 30000,
   "position": "within",
   "basis": "भारतात SUV साठी साधारण प्रकाशित कॉम्प्रिहेन्सिव्ह प्रीमियम श्रेणी. ती तुमच्या वाहनाच्या मूल्यानुसार किंवा शहरानुसार बदलत नाही.",
   "sources": [
    {
     "label": "Forbes Advisor India · Average cost of car insurance (2026)",
     "url": "https://www.forbes.com/advisor/in/car-insurance/average-cost-of-car-insurance/"
    }
   ]
  },
  "verdict": "तुमचे रिस्क प्रोफाइल कमी आहे. वर्षाला ₹23,910 असलेला हा अंदाज ₹15,000–₹30,000 या नेहमीच्या प्रकाशित श्रेणीत आहे.",
  "recommendations": [
   {
    "id": "renew-without-claim",
    "title": "क्लेम न करता नूतनीकरण करा",
    "description": "पुढील नूतनीकरणाच्या वेळी ओन-डॅमेज भागावरील तुमचा नो-क्लेम बोनस 25% वरून 35% होतो. तो गमावण्यापेक्षा छोटी दुरुस्ती स्वतःच्या पैशाने करणे स्वस्त पडू शकते.",
    "category": "HistoricalClaims",
    "estimatedSavingAmount": 2730,
    "estimatedSavingPercent": 11.4,
    "effort": "Medium",
    "impactPerEffort": 1365
   },
   {
    "id": "install-tracking-device",
    "title": "मान्यताप्राप्त अँटी-थेफ्ट डिव्हाइस बसवा",
    "description": "ARAI-मान्यताप्राप्त डिव्हाइस चोरीचा धोका कमी करते, आणि बहुतेक विमा कंपन्या त्यासाठी सूट देतात.",
    "category": "Behavioral",
    "estimatedSavingAmount": 510,
    "estimatedSavingPercent": 2.1,
    "effort": "Low",
    "impactPerEffort": 510
   },
   {
    "id": "increase-deductible",
    "title": "जास्त ऐच्छिक डिडक्टिबल निवडा",
    "description": "प्रत्येक क्लेमचा जास्त भाग तुम्ही स्वतः भरता, आणि प्रीमियम कमी होतो. ती रक्कम तुम्ही भरू शकत असाल तरच हे फायद्याचे आहे.",
    "category": "Behavioral",
    "estimatedSavingAmount": 410,
    "estimatedSavingPercent": 1.7,
    "effort": "Low",
    "impactPerEffort": 410
   },
   {
    "id": "reduce-mileage",
    "title": "कमी किलोमीटर गाडी चालवा",
    "description": "रस्त्यावर कमी वेळ म्हणजे अपघाताची कमी शक्यता. कमी प्रवासासाठी काही विमा कंपन्या पे-ॲज-यू-ड्राइव्ह प्लॅन देतात.",
    "category": "Behavioral",
    "estimatedSavingAmount": 340,
    "estimatedSavingPercent": 1.4,
    "effort": "Medium",
    "impactPerEffort": 170
   }
  ],
  "scenario": {
   "premium": 22660,
   "riskScore": 26,
   "steps": [
    23500,
    23000,
    22660
   ]
  },
  "answer": "क्लेम न करता नूतनीकरण करा. यामुळे वर्षाला सुमारे ₹2,730 (11.4%) वाचतील, आणि त्यासाठी मध्यम प्रयत्न लागतात. पुढील नूतनीकरणाच्या वेळी ओन-डॅमेज भागावरील तुमचा नो-क्लेम बोनस 25% वरून 35% होतो. तो गमावण्यापेक्षा छोटी दुरुस्ती स्वतःच्या पैशाने करणे स्वस्त पडू शकते."
 },
 "ta": {
  "applicant": {
   "personal": {
    "age": 29,
    "gender": "FEMALE",
    "occupation": "Product designer",
    "location": "Bengaluru",
    "annualIncome": 1800000,
    "maritalStatus": "SINGLE",
    "dependents": 0
   },
   "policy": {
    "insuranceType": "MOTOR",
    "coverageLevel": "STANDARD",
    "deductible": 0
   },
   "claimsLast12Months": 0,
   "recentClaimDatesIso": [],
   "motor": {
    "vehicleAgeYears": 3,
    "exShowroomPrice": 1400000,
    "vehicleValue": 840000,
    "claimFreeYears": 2,
    "vehicleType": "SUV",
    "engineCapacityCC": 1497,
    "annualMileageKm": 18000,
    "previousAccidents": 1,
    "previousClaims": 1,
    "drivingExperienceYears": 6,
    "trafficViolations": 1,
    "hasTrackingDevice": false
   }
  },
  "premium": {
   "basePremium": 18480,
   "riskMultiplier": 1.2,
   "coverageMultiplier": 1,
   "locationFactor": 1.11,
   "claimHistoryFactor": 1.11,
   "fraudAdjustment": 1,
   "deductibleFactor": 1,
   "ncbPercent": 25,
   "fixedPremium": 3416,
   "fixedPremiumLabel": "மூன்றாம் தரப்பு கவர் (IRDAI நிர்ணயித்தது)",
   "finalPremium": 23910,
   "currency": "INR"
  },
  "risk": {
   "riskScore": 33,
   "riskCategory": "Low",
   "factors": [
    {
     "name": "நகரின் போக்குவரத்து மற்றும் திருட்டு விகிதங்கள்",
     "category": "Geographic",
     "impact": 12.5,
     "direction": "negative",
     "description": "இந்த மாடல் உள்ளடக்கும் 20 நகரங்களில், போக்குவரத்து நெரிசல் மற்றும் வாகனத் திருட்டில் Bengaluru அதிக மதிப்பீடு பெறுகிறது."
    },
    {
     "name": "முந்தைய விபத்துகள்",
     "category": "HistoricalClaims",
     "impact": 6.6,
     "direction": "negative",
     "description": "பதிவில் ஒரு விபத்து உள்ளது. எதிர்கால க்ளெய்ம்களை முன்கணிப்பதில் கடந்த விபத்துகளே வலுவான அறிகுறி."
    },
    {
     "name": "முந்தைய க்ளெய்ம்கள்",
     "category": "HistoricalClaims",
     "impact": 4.8,
     "direction": "negative",
     "description": "முன்பு ஒரு க்ளெய்ம். ஒவ்வொரு க்ளெய்மும் உங்கள் நோ-க்ளெய்ம் போனஸையும் மீட்டமைக்கிறது."
    },
    {
     "name": "போக்குவரத்து விதிமீறல்கள்",
     "category": "Behavioral",
     "impact": 3.8,
     "direction": "negative",
     "description": "பதிவில் ஒரு போக்குவரத்து விதிமீறல்."
    },
    {
     "name": "ஓட்டுநர் வயது 25–29",
     "category": "Age",
     "impact": 3,
     "direction": "negative",
     "description": "29 வயதில் விபத்து விகிதம் இன்னும் சராசரிக்கு மேல் உள்ளது; இருபதுகளின் பிற்பகுதியில் அது குறைகிறது."
    },
    {
     "name": "ஆண்டுக்கு அதிக தூரம் ஓட்டுதல்",
     "category": "Behavioral",
     "impact": 2.5,
     "direction": "negative",
     "description": "ஆண்டுக்கு 18,000 km என்றால் சாலையில் அதிக நேரம், விபத்துக்கு அதிக வாய்ப்பு."
    }
   ]
  },
  "benchmark": {
   "applicable": true,
   "lowInr": 15000,
   "medianInr": 22500,
   "highInr": 30000,
   "position": "within",
   "basis": "இந்தியாவில் SUV-க்கான வெளியிடப்பட்ட வழக்கமான விரிவான பிரீமியம் வரம்பு. இது உங்கள் வாகனத்தின் மதிப்பு அல்லது நகரத்துக்கேற்ப மாறுவதில்லை.",
   "sources": [
    {
     "label": "Forbes Advisor India · Average cost of car insurance (2026)",
     "url": "https://www.forbes.com/advisor/in/car-insurance/average-cost-of-car-insurance/"
    }
   ]
  },
  "verdict": "உங்கள் ரிஸ்க் சுயவிவரம் குறைவு. ஆண்டுக்கு ₹23,910 என்ற இந்த மதிப்பீடு, வெளியிடப்பட்ட வழக்கமான வரம்புக்குள் (₹15,000–₹30,000) உள்ளது.",
  "recommendations": [
   {
    "id": "renew-without-claim",
    "title": "க்ளெய்ம் செய்யாமல் புதுப்பிக்கவும்",
    "description": "அடுத்த புதுப்பித்தலில், சொந்த சேதப் பகுதியில் உங்கள் நோ-க்ளெய்ம் போனஸ் 25%-இலிருந்து 35% ஆக மாறும். அதை இழப்பதை விட, சிறிய பழுதுக்கு நீங்களே பணம் செலுத்துவது மலிவாக இருக்கலாம்.",
    "category": "HistoricalClaims",
    "estimatedSavingAmount": 2730,
    "estimatedSavingPercent": 11.4,
    "effort": "Medium",
    "impactPerEffort": 1365
   },
   {
    "id": "install-tracking-device",
    "title": "அங்கீகரிக்கப்பட்ட திருட்டுத் தடுப்புச் சாதனத்தைப் பொருத்தவும்",
    "description": "ARAI அங்கீகரித்த சாதனம் திருட்டு அபாயத்தைக் குறைக்கிறது; பெரும்பாலான காப்பீட்டு நிறுவனங்கள் அதற்குத் தள்ளுபடி தருகின்றன.",
    "category": "Behavioral",
    "estimatedSavingAmount": 510,
    "estimatedSavingPercent": 2.1,
    "effort": "Low",
    "impactPerEffort": 510
   },
   {
    "id": "increase-deductible",
    "title": "அதிக தன்னார்வ டிடக்டிபிளைத் தேர்ந்தெடுக்கவும்",
    "description": "ஒவ்வொரு க்ளெய்மிலும் அதிகப் பகுதியை நீங்களே செலுத்துவீர்கள், பிரீமியம் குறையும். அந்தத் தொகையை உங்களால் சமாளிக்க முடிந்தால் மட்டுமே இது பயனுள்ளது.",
    "category": "Behavioral",
    "estimatedSavingAmount": 410,
    "estimatedSavingPercent": 1.7,
    "effort": "Low",
    "impactPerEffort": 410
   },
   {
    "id": "reduce-mileage",
    "title": "குறைவான கிலோமீட்டர் ஓட்டவும்",
    "description": "சாலையில் குறைந்த நேரம் என்றால் விபத்துக்கான வாய்ப்பு குறைவு. குறைவாக ஓட்டுபவர்களுக்குச் சில காப்பீட்டு நிறுவனங்கள் ஓட்டும் அளவுக்கேற்பக் கட்டணம் (pay-as-you-drive) திட்டங்களை வழங்குகின்றன.",
    "category": "Behavioral",
    "estimatedSavingAmount": 340,
    "estimatedSavingPercent": 1.4,
    "effort": "Medium",
    "impactPerEffort": 170
   }
  ],
  "scenario": {
   "premium": 22660,
   "riskScore": 26,
   "steps": [
    23500,
    23000,
    22660
   ]
  },
  "answer": "க்ளெய்ம் செய்யாமல் புதுப்பிக்கவும். இது ஆண்டுக்கு சுமார் ₹2,730 (11.4%) சேமிக்கும்; இதற்கு நடுத்தர அளவு முயற்சி தேவை. அடுத்த புதுப்பித்தலில், சொந்த சேதப் பகுதியில் உங்கள் நோ-க்ளெய்ம் போனஸ் 25%-இலிருந்து 35% ஆக மாறும். அதை இழப்பதை விட, சிறிய பழுதுக்கு நீங்களே பணம் செலுத்துவது மலிவாக இருக்கலாம்."
 },
 "te": {
  "applicant": {
   "personal": {
    "age": 29,
    "gender": "FEMALE",
    "occupation": "Product designer",
    "location": "Bengaluru",
    "annualIncome": 1800000,
    "maritalStatus": "SINGLE",
    "dependents": 0
   },
   "policy": {
    "insuranceType": "MOTOR",
    "coverageLevel": "STANDARD",
    "deductible": 0
   },
   "claimsLast12Months": 0,
   "recentClaimDatesIso": [],
   "motor": {
    "vehicleAgeYears": 3,
    "exShowroomPrice": 1400000,
    "vehicleValue": 840000,
    "claimFreeYears": 2,
    "vehicleType": "SUV",
    "engineCapacityCC": 1497,
    "annualMileageKm": 18000,
    "previousAccidents": 1,
    "previousClaims": 1,
    "drivingExperienceYears": 6,
    "trafficViolations": 1,
    "hasTrackingDevice": false
   }
  },
  "premium": {
   "basePremium": 18480,
   "riskMultiplier": 1.2,
   "coverageMultiplier": 1,
   "locationFactor": 1.11,
   "claimHistoryFactor": 1.11,
   "fraudAdjustment": 1,
   "deductibleFactor": 1,
   "ncbPercent": 25,
   "fixedPremium": 3416,
   "fixedPremiumLabel": "థర్డ్-పార్టీ కవర్ (IRDAI నిర్ణయించినది)",
   "finalPremium": 23910,
   "currency": "INR"
  },
  "risk": {
   "riskScore": 33,
   "riskCategory": "Low",
   "factors": [
    {
     "name": "నగరంలో ట్రాఫిక్, దొంగతనాల రేట్లు",
     "category": "Geographic",
     "impact": 12.5,
     "direction": "negative",
     "description": "ఈ మోడల్ పరిగణించే 20 నగరాల్లో, ట్రాఫిక్ రద్దీ మరియు వాహన దొంగతనాల్లో Bengaluru ఎక్కువ స్థాయిలో ఉంది."
    },
    {
     "name": "గత ప్రమాదాలు",
     "category": "HistoricalClaims",
     "impact": 6.6,
     "direction": "negative",
     "description": "రికార్డులో ఒక ప్రమాదం ఉంది. భవిష్యత్ క్లెయిమ్‌లను అంచనా వేయడంలో గత ప్రమాదాలే అత్యంత బలమైన సూచిక."
    },
    {
     "name": "గత క్లెయిమ్‌లు",
     "category": "HistoricalClaims",
     "impact": 4.8,
     "direction": "negative",
     "description": "గతంలో ఒక క్లెయిమ్. ప్రతి క్లెయిమ్ మీ నో-క్లెయిమ్ బోనస్‌ను కూడా సున్నాకు తెస్తుంది."
    },
    {
     "name": "ట్రాఫిక్ ఉల్లంఘనలు",
     "category": "Behavioral",
     "impact": 3.8,
     "direction": "negative",
     "description": "రికార్డులో ఒక ట్రాఫిక్ ఉల్లంఘన ఉంది."
    },
    {
     "name": "డ్రైవర్ వయసు 25–29",
     "category": "Age",
     "impact": 3,
     "direction": "negative",
     "description": "29 ఏళ్ల వయసులో ప్రమాదాల రేటు ఇంకా సగటు కంటే ఎక్కువగానే ఉంటుంది, ఇరవైల చివరి వరకు క్రమంగా తగ్గుతుంది."
    },
    {
     "name": "ఎక్కువ వార్షిక మైలేజ్",
     "category": "Behavioral",
     "impact": 2.5,
     "direction": "negative",
     "description": "సంవత్సరానికి 18,000 km అంటే రోడ్డుపై ఎక్కువ సమయం, ప్రమాదాలకు ఎక్కువ అవకాశం."
    }
   ]
  },
  "benchmark": {
   "applicable": true,
   "lowInr": 15000,
   "medianInr": 22500,
   "highInr": 30000,
   "position": "within",
   "basis": "భారతదేశంలో SUV కి సాధారణంగా ప్రచురించే కాంప్రహెన్సివ్ ప్రీమియం పరిధి. ఇది మీ వాహన విలువ లేదా నగరానికి అనుగుణంగా మారదు.",
   "sources": [
    {
     "label": "Forbes Advisor India · Average cost of car insurance (2026)",
     "url": "https://www.forbes.com/advisor/in/car-insurance/average-cost-of-car-insurance/"
    }
   ]
  },
  "verdict": "మీ రిస్క్ ప్రొఫైల్ తక్కువ. సంవత్సరానికి ₹23,910 తో, ఈ అంచనా సాధారణంగా ప్రచురించే పరిధి ₹15,000–₹30,000 లోపలే ఉంది.",
  "recommendations": [
   {
    "id": "renew-without-claim",
    "title": "క్లెయిమ్ చేయకుండా రెన్యూ చేయండి",
    "description": "తదుపరి రెన్యూవల్‌లో ఓన్-డ్యామేజ్ భాగంపై మీ నో-క్లెయిమ్ బోనస్ 25% నుండి 35% కు పెరుగుతుంది. దాన్ని కోల్పోవడం కంటే చిన్న రిపేర్‌కు మీరే చెల్లించడం చౌక కావచ్చు.",
    "category": "HistoricalClaims",
    "estimatedSavingAmount": 2730,
    "estimatedSavingPercent": 11.4,
    "effort": "Medium",
    "impactPerEffort": 1365
   },
   {
    "id": "install-tracking-device",
    "title": "ఆమోదిత యాంటీ-థెఫ్ట్ పరికరం అమర్చండి",
    "description": "ARAI-ఆమోదిత పరికరం దొంగతనం రిస్క్‌ను తగ్గిస్తుంది, చాలా బీమా సంస్థలు దానికి డిస్కౌంట్ ఇస్తాయి.",
    "category": "Behavioral",
    "estimatedSavingAmount": 510,
    "estimatedSavingPercent": 2.1,
    "effort": "Low",
    "impactPerEffort": 510
   },
   {
    "id": "increase-deductible",
    "title": "ఎక్కువ స్వచ్ఛంద డిడక్టిబుల్ ఎంచుకోండి",
    "description": "ప్రతి క్లెయిమ్‌లో ఎక్కువ భాగం మీరే చెల్లిస్తారు, ప్రీమియం తగ్గుతుంది. ఆ మొత్తాన్ని మీరు భరించగలిగితేనే ఇది లాభం.",
    "category": "Behavioral",
    "estimatedSavingAmount": 410,
    "estimatedSavingPercent": 1.7,
    "effort": "Low",
    "impactPerEffort": 410
   },
   {
    "id": "reduce-mileage",
    "title": "తక్కువ కిలోమీటర్లు నడపండి",
    "description": "రోడ్డుపై తక్కువ సమయం అంటే ప్రమాదాలకు తక్కువ అవకాశం. తక్కువ మైలేజ్ కోసం కొన్ని బీమా సంస్థలు pay-as-you-drive ప్లాన్‌లు అందిస్తాయి.",
    "category": "Behavioral",
    "estimatedSavingAmount": 340,
    "estimatedSavingPercent": 1.4,
    "effort": "Medium",
    "impactPerEffort": 170
   }
  ],
  "scenario": {
   "premium": 22660,
   "riskScore": 26,
   "steps": [
    23500,
    23000,
    22660
   ]
  },
  "answer": "క్లెయిమ్ చేయకుండా రెన్యూ చేయండి. దీనివల్ల సంవత్సరానికి సుమారు ₹2,730 (11.4%) ఆదా అవుతుంది, దీనికి మధ్యస్థ శ్రమ అవసరం. తదుపరి రెన్యూవల్‌లో ఓన్-డ్యామేజ్ భాగంపై మీ నో-క్లెయిమ్ బోనస్ 25% నుండి 35% కు పెరుగుతుంది. దాన్ని కోల్పోవడం కంటే చిన్న రిపేర్‌కు మీరే చెల్లించడం చౌక కావచ్చు."
 },
 "kn": {
  "applicant": {
   "personal": {
    "age": 29,
    "gender": "FEMALE",
    "occupation": "Product designer",
    "location": "Bengaluru",
    "annualIncome": 1800000,
    "maritalStatus": "SINGLE",
    "dependents": 0
   },
   "policy": {
    "insuranceType": "MOTOR",
    "coverageLevel": "STANDARD",
    "deductible": 0
   },
   "claimsLast12Months": 0,
   "recentClaimDatesIso": [],
   "motor": {
    "vehicleAgeYears": 3,
    "exShowroomPrice": 1400000,
    "vehicleValue": 840000,
    "claimFreeYears": 2,
    "vehicleType": "SUV",
    "engineCapacityCC": 1497,
    "annualMileageKm": 18000,
    "previousAccidents": 1,
    "previousClaims": 1,
    "drivingExperienceYears": 6,
    "trafficViolations": 1,
    "hasTrackingDevice": false
   }
  },
  "premium": {
   "basePremium": 18480,
   "riskMultiplier": 1.2,
   "coverageMultiplier": 1,
   "locationFactor": 1.11,
   "claimHistoryFactor": 1.11,
   "fraudAdjustment": 1,
   "deductibleFactor": 1,
   "ncbPercent": 25,
   "fixedPremium": 3416,
   "fixedPremiumLabel": "ಥರ್ಡ್-ಪಾರ್ಟಿ ಕವರ್ (IRDAI ನಿಗದಿಪಡಿಸಿದ್ದು)",
   "finalPremium": 23910,
   "currency": "INR"
  },
  "risk": {
   "riskScore": 33,
   "riskCategory": "Low",
   "factors": [
    {
     "name": "ನಗರದ ಸಂಚಾರ ಮತ್ತು ಕಳ್ಳತನ ಪ್ರಮಾಣ",
     "category": "Geographic",
     "impact": 12.5,
     "direction": "negative",
     "description": "ಈ ಮಾಡೆಲ್ ಒಳಗೊಂಡಿರುವ 20 ನಗರಗಳಲ್ಲಿ, ಸಂಚಾರ ದಟ್ಟಣೆ ಮತ್ತು ವಾಹನ ಕಳ್ಳತನದಲ್ಲಿ Bengaluru ನಗರದ ರೇಟಿಂಗ್ ಹೆಚ್ಚು."
    },
    {
     "name": "ಹಿಂದಿನ ಅಪಘಾತಗಳು",
     "category": "HistoricalClaims",
     "impact": 6.6,
     "direction": "negative",
     "description": "ದಾಖಲೆಯಲ್ಲಿ ಒಂದು ಅಪಘಾತವಿದೆ. ಭವಿಷ್ಯದ ಕ್ಲೈಮ್‌ಗಳನ್ನು ಅತ್ಯಂತ ಬಲವಾಗಿ ಸೂಚಿಸುವುದು ಹಿಂದಿನ ಅಪಘಾತಗಳು."
    },
    {
     "name": "ಹಿಂದಿನ ಕ್ಲೈಮ್‌ಗಳು",
     "category": "HistoricalClaims",
     "impact": 4.8,
     "direction": "negative",
     "description": "ಹಿಂದೆ ಒಂದು ಕ್ಲೈಮ್. ಪ್ರತಿ ಕ್ಲೈಮ್‌ನಿಂದ ನಿಮ್ಮ ನೋ-ಕ್ಲೈಮ್ ಬೋನಸ್ ಕೂಡ ಮತ್ತೆ ಮೊದಲಿನಿಂದ ಶುರುವಾಗುತ್ತದೆ."
    },
    {
     "name": "ಸಂಚಾರ ನಿಯಮ ಉಲ್ಲಂಘನೆಗಳು",
     "category": "Behavioral",
     "impact": 3.8,
     "direction": "negative",
     "description": "ದಾಖಲೆಯಲ್ಲಿ ಒಂದು ಸಂಚಾರ ನಿಯಮ ಉಲ್ಲಂಘನೆ ಇದೆ."
    },
    {
     "name": "ಚಾಲಕರ ವಯಸ್ಸು 25–29",
     "category": "Age",
     "impact": 3,
     "direction": "negative",
     "description": "29 ವಯಸ್ಸಿನಲ್ಲಿ ಅಪಘಾತದ ಪ್ರಮಾಣ ಇನ್ನೂ ಸರಾಸರಿಗಿಂತ ಹೆಚ್ಚು; ಇದು ಇಪ್ಪತ್ತರ ಕೊನೆಯ ವರ್ಷಗಳಲ್ಲಿ ಕಡಿಮೆಯಾಗುತ್ತಾ ಹೋಗುತ್ತದೆ."
    },
    {
     "name": "ಹೆಚ್ಚಿನ ವಾರ್ಷಿಕ ಮೈಲೇಜ್",
     "category": "Behavioral",
     "impact": 2.5,
     "direction": "negative",
     "description": "ವರ್ಷಕ್ಕೆ 18,000 km ಎಂದರೆ ರಸ್ತೆಯಲ್ಲಿ ಹೆಚ್ಚು ಸಮಯ ಮತ್ತು ಅಪಘಾತಗಳ ಹೆಚ್ಚಿನ ಅಪಾಯ."
    }
   ]
  },
  "benchmark": {
   "applicable": true,
   "lowInr": 15000,
   "medianInr": 22500,
   "highInr": 30000,
   "position": "within",
   "basis": "ಭಾರತದಲ್ಲಿ SUV ಗೆ ಸಾಮಾನ್ಯ ಪ್ರಕಟಿತ ಕಾಂಪ್ರಹೆನ್ಸಿವ್ ಪ್ರೀಮಿಯಂ ಶ್ರೇಣಿ. ಇದು ನಿಮ್ಮ ವಾಹನದ ಮೌಲ್ಯ ಅಥವಾ ನಗರಕ್ಕೆ ತಕ್ಕಂತೆ ಬದಲಾಗುವುದಿಲ್ಲ.",
   "sources": [
    {
     "label": "Forbes Advisor India · Average cost of car insurance (2026)",
     "url": "https://www.forbes.com/advisor/in/car-insurance/average-cost-of-car-insurance/"
    }
   ]
  },
  "verdict": "ನಿಮ್ಮ ರಿಸ್ಕ್ ಪ್ರೊಫೈಲ್ ಕಡಿಮೆ. ವರ್ಷಕ್ಕೆ ₹23,910 ಆಗಿರುವ ಈ ಅಂದಾಜು ಸಾಮಾನ್ಯ ಪ್ರಕಟಿತ ಶ್ರೇಣಿಯ (₹15,000–₹30,000) ಒಳಗಿದೆ.",
  "recommendations": [
   {
    "id": "renew-without-claim",
    "title": "ಕ್ಲೈಮ್ ಮಾಡದೆ ನವೀಕರಿಸಿ",
    "description": "ಮುಂದಿನ ನವೀಕರಣದಲ್ಲಿ ಓನ್-ಡ್ಯಾಮೇಜ್ ಭಾಗದ ಮೇಲಿನ ನಿಮ್ಮ ನೋ-ಕ್ಲೈಮ್ ಬೋನಸ್ 25% ನಿಂದ 35% ಆಗುತ್ತದೆ. ಅದನ್ನು ಕಳೆದುಕೊಳ್ಳುವುದಕ್ಕಿಂತ ಸಣ್ಣ ರಿಪೇರಿಗೆ ನೀವೇ ಹಣ ಪಾವತಿಸುವುದು ಅಗ್ಗವಾಗಬಹುದು.",
    "category": "HistoricalClaims",
    "estimatedSavingAmount": 2730,
    "estimatedSavingPercent": 11.4,
    "effort": "Medium",
    "impactPerEffort": 1365
   },
   {
    "id": "install-tracking-device",
    "title": "ಅನುಮೋದಿತ ಕಳ್ಳತನ-ತಡೆ ಸಾಧನ ಅಳವಡಿಸಿ",
    "description": "ARAI-ಅನುಮೋದಿತ ಸಾಧನವು ಕಳ್ಳತನದ ಅಪಾಯವನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ, ಮತ್ತು ಹೆಚ್ಚಿನ ವಿಮಾ ಕಂಪನಿಗಳು ಅದಕ್ಕೆ ರಿಯಾಯಿತಿ ನೀಡುತ್ತವೆ.",
    "category": "Behavioral",
    "estimatedSavingAmount": 510,
    "estimatedSavingPercent": 2.1,
    "effort": "Low",
    "impactPerEffort": 510
   },
   {
    "id": "increase-deductible",
    "title": "ಹೆಚ್ಚಿನ ಸ್ವಯಂಪ್ರೇರಿತ ಡಿಡಕ್ಟಿಬಲ್ ಆಯ್ಕೆಮಾಡಿ",
    "description": "ಪ್ರತಿ ಕ್ಲೈಮ್‌ನ ಹೆಚ್ಚಿನ ಭಾಗವನ್ನು ನೀವೇ ಪಾವತಿಸುತ್ತೀರಿ, ಮತ್ತು ಪ್ರೀಮಿಯಂ ಕಡಿಮೆಯಾಗುತ್ತದೆ. ಆ ಮೊತ್ತವನ್ನು ನೀವು ಭರಿಸಬಲ್ಲಿರಾದರೆ ಮಾತ್ರ ಇದು ಲಾಭದಾಯಕ.",
    "category": "Behavioral",
    "estimatedSavingAmount": 410,
    "estimatedSavingPercent": 1.7,
    "effort": "Low",
    "impactPerEffort": 410
   },
   {
    "id": "reduce-mileage",
    "title": "ಕಡಿಮೆ ಕಿಲೋಮೀಟರ್ ಚಲಾಯಿಸಿ",
    "description": "ರಸ್ತೆಯಲ್ಲಿ ಕಡಿಮೆ ಸಮಯ ಎಂದರೆ ಅಪಘಾತದ ಕಡಿಮೆ ಸಾಧ್ಯತೆ. ಕಡಿಮೆ ಮೈಲೇಜ್‌ಗೆ ಕೆಲವು ವಿಮಾ ಕಂಪನಿಗಳು ಪೇ-ಆ್ಯಸ್-ಯು-ಡ್ರೈವ್ ಪ್ಲಾನ್‌ಗಳನ್ನು ನೀಡುತ್ತವೆ.",
    "category": "Behavioral",
    "estimatedSavingAmount": 340,
    "estimatedSavingPercent": 1.4,
    "effort": "Medium",
    "impactPerEffort": 170
   }
  ],
  "scenario": {
   "premium": 22660,
   "riskScore": 26,
   "steps": [
    23500,
    23000,
    22660
   ]
  },
  "answer": "ಕ್ಲೈಮ್ ಮಾಡದೆ ನವೀಕರಿಸಿ. ಇದರಿಂದ ವರ್ಷಕ್ಕೆ ಸುಮಾರು ₹2,730 (11.4%) ಉಳಿತಾಯವಾಗುತ್ತದೆ, ಮತ್ತು ಇದಕ್ಕೆ ಮಧ್ಯಮ ಶ್ರಮ ಬೇಕು. ಮುಂದಿನ ನವೀಕರಣದಲ್ಲಿ ಓನ್-ಡ್ಯಾಮೇಜ್ ಭಾಗದ ಮೇಲಿನ ನಿಮ್ಮ ನೋ-ಕ್ಲೈಮ್ ಬೋನಸ್ 25% ನಿಂದ 35% ಆಗುತ್ತದೆ. ಅದನ್ನು ಕಳೆದುಕೊಳ್ಳುವುದಕ್ಕಿಂತ ಸಣ್ಣ ರಿಪೇರಿಗೆ ನೀವೇ ಹಣ ಪಾವತಿಸುವುದು ಅಗ್ಗವಾಗಬಹುದು."
 }
} as unknown as Record<Lang, LandingSample>;
