// Regenerates frontend/src/pages/landing/sample.ts from the real engine, once
// per language, so the landing page never shows invented numbers or
// untranslated engine text. Run from the repo root after pricing or
// translations change:  npx --prefix backend tsx scripts/gen-landing-sample.ts
import fs from "node:fs";
import { LANGUAGES } from "@insurtechai/shared";
import { runFullAssessment } from "../backend/src/engine/assess";
import { answerAdvisorQuestion } from "../backend/src/engine/advisor";
import { withLang } from "../backend/src/i18n";

// 29, Bengaluru, 3-year-old SUV (₹14 lakh ex-showroom), one accident and one
// claim three years ago, claim-free for the two years since (25% NCB).
const applicant: any = {
  personal: { age: 29, gender: "FEMALE", occupation: "Product designer", location: "Bengaluru", annualIncome: 1800000, maritalStatus: "SINGLE", dependents: 0 },
  policy: { insuranceType: "MOTOR", coverageLevel: "STANDARD", deductible: 0 },
  claimsLast12Months: 0,
  recentClaimDatesIso: [],
  motor: {
    vehicleAgeYears: 3, exShowroomPrice: 1400000, vehicleValue: 840000, claimFreeYears: 2, vehicleType: "SUV", engineCapacityCC: 1497,
    annualMileageKm: 18000, previousAccidents: 1, previousClaims: 1, drivingExperienceYears: 6, trafficViolations: 1, hasTrackingDevice: false,
  },
};

function build() {
  const result = runFullAssessment(applicant);
  const s1 = structuredClone(applicant); s1.policy.deductible = 25000;
  const s2 = structuredClone(s1); s2.motor.hasTrackingDevice = true;
  const s3 = structuredClone(s2); s3.motor.annualMileageKm = 12000;
  const r3 = runFullAssessment(s3);
  return {
    applicant: { ...applicant, motor: { ...applicant.motor, vehicleValue: result.motorValue!.idv } },
    premium: result.premium,
    risk: { riskScore: result.risk.riskScore, riskCategory: result.risk.riskCategory, factors: result.risk.factors },
    benchmark: result.decisionSummary.benchmark,
    verdict: result.decisionSummary.verdict,
    recommendations: result.recommendations,
    scenario: { premium: r3.premium.finalPremium, riskScore: r3.risk.riskScore, steps: [runFullAssessment(s1).premium.finalPremium, runFullAssessment(s2).premium.finalPremium, r3.premium.finalPremium] },
    answer: answerAdvisorQuestion("HOW_TO_REDUCE", result),
  };
}

const samples = Object.fromEntries(LANGUAGES.map((l) => [l.code, withLang(l.code, build)]));
const en = samples.en as ReturnType<typeof build>;
console.log(en.premium.finalPremium, en.risk.riskScore, en.risk.riskCategory, en.benchmark.position, en.scenario, en.recommendations.map((r) => [r.id, r.estimatedSavingAmount]));

const out = `// Generated by scripts/gen-landing-sample.ts from the real engine, one entry per
// language. Don't edit by hand: the landing page must never show invented numbers.
import type { ApplicantProfile, PremiumBreakdown, RiskFactorContribution, MarketBenchmark, Recommendation, RiskCategory, Lang } from "@insurtechai/shared";

export interface LandingSample {
  applicant: ApplicantProfile;
  premium: PremiumBreakdown;
  risk: { riskScore: number; riskCategory: RiskCategory; factors: RiskFactorContribution[] };
  benchmark: MarketBenchmark;
  verdict: string;
  recommendations: Recommendation[];
  scenario: { premium: number; riskScore: number; steps: number[] };
  answer: string;
}

export const SAMPLES = ${JSON.stringify(samples, null, 1)} as unknown as Record<Lang, LandingSample>;
`;
fs.writeFileSync(new URL("../frontend/src/pages/landing/sample.ts", import.meta.url), out);
