// Builds shared/src/i18n/catalogs/<lang>.ts from scripts/i18n/<lang>/*.json
// (translator output, {"English": "translation"}) and checks them against
// scripts/i18n/source.json. Run: node scripts/i18n-build.mjs [lang...]
//
// Fails on: placeholder mismatch, empty translations. Reports: missing and
// stale keys (English falls back at runtime, so missing isn't fatal).
import fs from "node:fs";
import path from "node:path";

const source = JSON.parse(fs.readFileSync("scripts/i18n/source.json", "utf8"));
const langs = process.argv.slice(2).length ? process.argv.slice(2) : ["hi", "mr", "ta", "te", "kn"];
const vars = (s) => [...s.matchAll(/\{([a-zA-Z]+)\}/g)].map((m) => m[1]).sort().join(",");
let failed = false;

for (const lang of langs) {
  const dir = path.join("scripts/i18n", lang);
  const merged = {};
  if (fs.existsSync(dir)) {
    for (const f of fs.readdirSync(dir).filter((f) => f.endsWith(".json")).sort()) {
      Object.assign(merged, JSON.parse(fs.readFileSync(path.join(dir, f), "utf8")));
    }
  }
  const errors = [];
  const catalog = {};
  for (const [en, tr] of Object.entries(merged)) {
    if (!(en in source)) continue; // stale: dropped from the catalog
    if (typeof tr !== "string" || !tr.trim()) { errors.push(`empty: ${en}`); continue; }
    if (vars(en) !== vars(tr)) { errors.push(`placeholders differ: ${en}  =>  ${tr}`); continue; }
    catalog[en] = tr;
  }
  const missing = Object.keys(source).filter((k) => !(k in catalog));
  const stale = Object.keys(merged).filter((k) => !(k in source));
  const body =
    "// Generated by scripts/i18n-build.mjs from scripts/i18n/" + lang + "/*.json. Don't edit by hand.\n" +
    "const catalog: Record<string, string> = " + JSON.stringify(catalog, null, 2) + ";\nexport default catalog;\n";
  fs.writeFileSync(`shared/src/i18n/catalogs/${lang}.ts`, body);
  console.log(`${lang}: ${Object.keys(catalog).length}/${Object.keys(source).length} translated, ${missing.length} missing, ${stale.length} stale, ${errors.length} errors`);
  if (errors.length) { failed = true; errors.slice(0, 20).forEach((e) => console.log("  " + e)); }
  if (missing.length && missing.length <= 30) missing.forEach((m) => console.log("  missing: " + m));
}
process.exit(failed ? 1 : 0);
